### ISSUE TITLE
Allow OSX testing in circle

### ISSUE THREAD

**Issue by keroserene** [keroserene/go-webrtc#11]

**Comment by arlolra** [comment]
Doesn't seem like it's possible to build on more than one OS on CircleCI.
https://discuss.circleci.com/t/how-to-use-circleci-for-linux-xcode-in-one-project/693

However, this is possible on TravisCI.
https://docs.travis-ci.com/user/multi-os/#Setting-.travis.yml

Why was it necessary to switch to CircleCI? Otherwise we can close this as declined.

**Comment by keroserene** [comment]
Oh no! Thought there might be some way to use multiple containers?

Originally, the switch to CircleCI was due to how easy it was to upgrade GCC to the right version, (took just minutes to figure out the right config) whereas on Travis GCC it was more mystifying / less documented, GCC seemed always stuck at 4.6, the old `sudo apt-get` method no longer worked because `sudo` was no longer available. So there was never a successful build on Travis, and I felt too much time was spent figuring it out.

However, if you do figure out how to upgrade GCC and build successfully on Travis, then we could totally switch to Travis :)

**Comment by arlolra** [comment]
Ok, I got OS X building on TravisCI. I'll see what I can do about GCC on Linux there ... so we don't have to maintain two different CIs.

**Comment by arlolra** [comment]
Alright, travis is now building both OSs. Marking this done.

**Comment by keroserene** [comment]
:+1:
