### ISSUE TITLE
Re-enable -race in CI

### ISSUE THREAD

**Issue by arlolra** [keroserene/go-webrtc#24]
Running the tests with `-race` fails (I've even seen it segfault).

This was on by default in our CircleCI config (apparently that wasn't doing a good job of reporting failures) but is now disabled on TravisCI.

Should probably get to the bottom of it then re-enable in CI.

**Comment by keroserene** [comment]
Segfault is happening in one of the RTP Media threads... in `webrtc::AudioDeviceLinuxPulse::TerminatePulseAudio()`, deep within `cricket::WebRtcVoiceEngine::Terminate()`.

This might be related to the spurious ALSA messages that show up in the test logs too...

There may be some specific PeerConnection media constraint we can specify to avoid this... or maybe a minimal / fake audio provider needs to happen somewhere so that whatever required reference does exist.

Also, once #10 happens, I suspect this should stop. Will poke more at this later
