### ISSUE TITLE
Integrating Go-WebRTC for IP camera streaming

### ISSUE THREAD

**Issue by ankits1234** [keroserene/go-webrtc#40]
Hello,

We have an IP camera solution based on Android using the stagefright framework. We are using Live555 for RTSP streaming and also using Go server.  

I would like to know if the go-webrtc package is stable enough for Audio/Video streaming to be used for production. 

Also, does go-webrtc support H264 codec since we already have H264 content for RTSP streaming?

If yes, please provide demo code for testing AV streaming using go-webrtc.

regards
Ankit Singhal

**Comment by keroserene** [comment]
Hi Ankit,

Currently, go-webrtc only supports DataChannels, as that was the most urgent use-case motivating my work here. MediaChannels are certainly feasible to work in, given the structures already built in this library, but require a significant chunk of development. I do plan to do this in the future, but pull requests and/or support for this work are certainly welcome as well!

Best,
~serene

**Comment by ankits1234** [comment]
Hello Serene,

Thanks for your response. Can you please answer few of my doubts regarding
the webRTC and suggest how can i use it?

1. There is a getUserMedia API used in webRTC for media. I believe it is
supported in the browser and not really part of webRTC and it is coupled
with webcam and microphone of the device. How can i use webRTC and pass on
the AV captured through our IP cam and also encoded using H264 encoder.

2. We can not integrate any browser like chrome or firefox since they are
too heavy. We are using Go server. So how can we plan to integrate the AV
part with webRTC using Go.

3. As far as i know, the webRTC generates a URL which can be used by
clients. It is something like RTSP or http url. Can you please confirm?

4. Can we support broadcasting to multiple clients using Go server?

It would be helpful to have your response. Please let me know if something
is not clear.

regards
Ankit Singhal

regards
Ankit Singhal

**Comment by keroserene** [comment]
Hi Ankit,

For 1, 2, it seems in general you'll need to familiarize with the native code, which also includes codecs that might be relevant to your interests. Understanding the C++ library (you can look at how I've wrapped it with cgo + the C adapting layer in this repo) will be required to implement the Go wrapper in a way that meets your needs:  https://webrtc.org/native-code/development/
3. All WebRTC does is provide machinery for ICE negotiation. All it generates are SDP offers and answers. It's up to you to arrange signalling in order to establish peer connections.
4. Yes, though basic WebRTC is strictly peer-to-peer, so you'll need to do additional work to support broadcasting.

Hope this helps,
~serene
