### ISSUE TITLE
Installation fails on Arch after pkg-config was replaced with pkgconf

### ISSUE THREAD

**Issue by 26000** [keroserene/go-webrtc#89]
```
$ go get -u github.com/keroserene/go-webrtc
# github.com/keroserene/go-webrtc
cc1: error: webrtc-linux-amd64.pc/include: Not a directory
```

Works after downgrading to pkg-config...

**Comment by fflo** [comment]
any update on this issue?

Compiling on Alpine fails with:
`# github.com/keroserene/go-webrtc
cc1: error: webrtc-linux-amd64.pc/include: Not a directory`

**Comment by uumaro** [comment]
This looks like a bug in pkgconf. The go-webrtc .pc files use the [`${pcfiledir}`](http://www.linuxhowtos.org/manpages/1/pkg-config.htm#lbAG) derived variable. pkgconf [sets](https://git.dereferenced.org/pkgconf/pkgconf/src/commit/db9c1e96a12bfbb171dfe85d5312ac311f62d876/libpkgconf/pkg.c#L353-L354) `${pcfiledir}` by calling [`pkg_get_parent_dir`](https://git.dereferenced.org/pkgconf/pkgconf/src/commit/db9c1e96a12bfbb171dfe85d5312ac311f62d876/libpkgconf/pkg.c#L52), and `pkg_get_parent_dir` has a bug whenever the path doesn't contain a directory separator: it returns the original path instead of returning `"."`.

Please report the bug at the [pkgconf issue tracker](https://git.dereferenced.org/pkgconf/pkgconf/issues).
